### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by PottiMc** [SoulOfNoob/MMM-NextCloud-Tasks#5]
I freshly installed the NextCloudTasks Module 2 days ago. It was not working in the beginning because of a self signed certificate (mentioned in another issue). I corrected that and it worked fine for 2 days. Now I get new errorlogs mentioning the following:

[25.04.2021 14:46.37.409] [ERROR]
0|MagicMirror  | WebDav RangeError: Maximum call stack size exceeded
0|MagicMirror  |     at findParent (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:4:20)
0|MagicMirror  |     at findParent (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:13:31)
0|MagicMirror  |     at transformData (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:34:26)
0|MagicMirror  |     at transformData (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:55:16)
0|MagicMirror  |     at transformData (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:55:16)
0|MagicMirror  |     at transformData (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:55:16)
0|MagicMirror  |     at transformData (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:55:16)
0|MagicMirror  |     at transformData (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:55:16)
0|MagicMirror  |     at transformData (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:55:16)
0|MagicMirror  |     at transformData (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/transformer.js:55:16)

What can I do to prevent these errors?

**Comment by PottiMc** [comment]
I managed to track it down a little bit. The error is connected to subtasks. If I create subtasks on my phone with my tasks.org app and DAVX5 synchronisation I run into this error. If I create subtasks in the Nextcloud Browser version with tasks it works and is shown on the mirror.

However, my phone created subtasks are shown normally in the Nextcloud browser version with no difference at all.

**Comment by Archonw** [comment]
I agree. I have the same problem. Without any subtasks it works fine. But it will also not work, if i create subtasks over the webbrowser in nextcloud.

**Comment by starlingfire** [comment]
I was able to resolve this issue locally by modifying the following line:

https://github.com/SoulOfNoob/MMM-NextCloud-Tasks/blob/1d173bcdc807cac87aac2cf937aa07f7cb42bd4c/webDavHelper.js#L15

I added the check to exclude completed items here
```js
if (element.type === 'VTODO' && element.status !== "COMPLETED") elements.push(element);
```

A more holistic solution would be to also include the check for the `hideCompletedTasks` config, but I'm always hiding them, so I'm okay hard-coding this.

**Comment by starlingfire** [comment]
I researched this issue some more and found the root cause. @PottiMc hit the nail on the head with different applications creating subtasks with slightly different JSON in the "related-to" key. Compare the two below:
```json
{
    "type": "VTODO",
    "params": [],
    "uid": "01047820-e10e-458b-a49c-ea7bfbaf5d35",
    "created": "2022-05-11T18:53:20.000Z",
    "lastmodified": "2022-05-11T18:53:20.000Z",
    "dtstamp": "2022-05-11T18:53:20.000Z",
    "summary": "First type of subtask",
    "related-to": "36afe9f3-c233-437b-ab42-3c48471148c5"
}
{
    "type": "VTODO",
    "params": [],
    "dtstamp": "2022-05-10T16:09:58.000Z",
    "uid": "a54e54bf-3744-4f2a-a02c-a7dbfe7028f4",
    "sequence": "1",
    "created": "2022-05-10T09:19:40.000Z",
    "lastmodified": "2022-05-10T16:09:19.000Z",
    "summary": "Second type of subtask",
    "status": "NEEDS-ACTION",
    "related-to": {
        "params": {
            "RELTYPE": "PARENT"
        },
        "val": "a273153a-18ef-4c6e-83fd-3ecae8707b5a"
    }
}
```
In the first example, the UID is stored directly in the `related-to` key, while in the latter it's stored in the `val` key nested within the `related-to` key. I can't be sure how the former was created, as all my testing in both the browser and on the app with CardDAV sync yielded the latter layout. Possibly the former was created from an old version of one of the implementations? 

The bug occurs in the `findParents` recursive loop, but since it's checking the `related-to` value directly, it never finds the parent, because that's not where the UID is stored. My fix simply involves checking if `val` is present, and if so, use that, otherwise use the `related-to` value.

Note: The reason my "fix" from two weeks ago worked is because I no longer use subtasks, so filtering them out meant I didn't experience the bug anymore. 

@SoulOfNoob I submitted a PR above with this fix. Please review and merge if it looks good.

**Comment by starlingfire** [comment]
@PottiMc  & @Archonw, I have forked this repo and fixed this issue. I also added features for sort options and colorized icons. Check it out! https://github.com/starlingfire/MMM-NextCloud-Tasks

**Comment by PottiMc** [comment]
It actually took me very long to test, sorry for that. But your fork is working fine! Thank you!
